// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgzwueeqaobzpamwddzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnend1ZWVxYW9ienBhbXdkZHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTgzNDgsImV4cCI6MjA2NzU5NDM0OH0.QXdfeaohy-zDFP-tD7yA6j7ckquQEt4uG9Rd937RnN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});